// <auto-generated />
using CompensationRetirementEstimator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompensationRetirementEstimator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806232659_LinkProjectionsToUsers")]
    partial class LinkProjectionsToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CompensationRetirementEstimator.Api.Models.RetirementProjection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ContributionRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerMatchRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestmentGrowthRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProjectedMonthlyIncome")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RetirementSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RetirementProjections");
                });

            modelBuilder.Entity("CompensationRetirementEstimator.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CompensationRetirementEstimator.Api.Models.RetirementProjection", b =>
                {
                    b.HasOne("CompensationRetirementEstimator.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
